query Comments($reputationObjectId: String!) {
  comments(reputationObjectId: $reputationObjectId) {
    comment
    createdAt
    id
    parentId
    reputationObjectId
  }
  commentsTotal(reputationObjectId: $reputationObjectId)
}
