query LikesFeed($userId: String!, $page: Int) {
  likesFeed(userId: $userId, page: $page) {
    createdAt
    authorId
    isPositive
    reputationObjectId
    reputationObjectType
    reputationObject {
      __typename
      ... on Comment {
        id
        reputationObjectId
        parentId
        comment
        createdAt
        authorId
        author {
          id
          username
        }
      }
      ... on Organization {
        _id
        titlerus
        titleeng
        description
        tag
        rating
        foto
        country
        commentsTotal
      }
      ... on Person {
        _id
        titlerus
        titleeng
        description
        tag
        rating
        foto
        dob
        gender
        country
        commentsTotal
      }
    }
  }
}
