query GetPosts($authorId: String, $lazyLoadEvent: LazyLoadEvent) {
  posts(authorId: $authorId, lazyLoadEvent: $lazyLoadEvent) {
    post
    preview
    tags
    title
    createdAt
    authorId
    _id
    commentsTotal
  }
  postsTotal(authorId: $authorId, lazyLoadEvent: $lazyLoadEvent)
}
