mutation UpdateProfile($profile: ProfileInput!) {
  updateProfile (profile: $profile) {
    userId
    nickname
    info
    education
    marital
    children
    workposition
    work
    place
    income
    race
    citizenship
    location
    gender
    orientation
    religion
    politicalstand
    __typename
  }
}
