query GetProfile($nickname: String) {
  profile(nickname: $nickname) {
    userId
    birthday
    nickname
    info
    education
    marital
    children
    workposition
    work
    place
    income
    race
    citizenship
    location
    gender
    orientation
    religion
    politicalstand
    interests
  }
}
